### ISSUE TITLE
Cursos Ruby - Roadmap GitHub

### ISSUE THREAD

**Issue by marcelolx** [marcelolx/ruby-cursos#4]
https://github.com/EvertonLopes/Ruby-Roadmap#2%C2%BA-passo---aprenda-a-linguagem-ruby

- [ ] Ler o seguinte livro https://leanpub.com/conhecendo-ruby
- [ ] Ler o seguinte livro https://books.goalkicker.com/RubyBook/
- [ ] Curso Ruby Puro https://onebitcode.com/course/ruby-puro/
- [ ] Fazer os cursos de ruby que tem aqui https://www.codesaga.com.br/
* Fazer execícios nos seguintes sites para fixar
  - [ ] https://www.urionlinejudge.com.br/judge/en/login
  - [ ] https://www.hackerrank.com/
  - [ ] https://exercism.io/
